services:
  - type: web
    name: unilex-api
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: unilex-frontend
    runtime: static
    plan: free
    buildCommand: ""
    staticPublishPath: frontend
